# Generated by Django 5.0 on 2023-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='имя персоны'),
        ),
    ]
