# Generated by Django 5.0 on 2023-12-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0003_alter_message_name_alter_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='santa.message', verbose_name='связь с окном'),
        ),
    ]
