# Generated by Django 5.0 on 2023-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0004_alter_answer_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username пользователя')),
            ],
        ),
    ]
