# Generated by Django 5.0 on 2023-12-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0005_allowedidentifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.IntegerField(blank=True, null=True, verbose_name='id персоны'),
        ),
    ]
