# Generated by Django 5.0 on 2023-12-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0006_remove_person_chat_id_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='username персоны'),
        ),
    ]
