# Generated by Django 5.0 on 2023-12-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0007_alter_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='пароль'),
        ),
    ]
