# Generated by Django 5.0 on 2023-12-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0008_party_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phonenumber',
        ),
    ]
