# Generated by Django 5.0 on 2023-12-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0010_remove_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='password',
        ),
    ]
