# Generated by Django 5.0 on 2023-12-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0011_remove_party_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='santa.party', verbose_name='В какой игре'),
        ),
    ]
