# Generated by Django 5.0 on 2023-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0012_answer_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chat_id',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='id персоны'),
        ),
    ]
